### ISSUE TITLE
File upload: histogram representation deployment fails

### ISSUE THREAD

**Issue by chlmarchal** [Cytomine-ULiege/pims-plugin-format-bioformats#4]
I am trying to upload a CZI file from https://downloads.openmicroscopy.org/images/Zeiss-CZI using this plugin. However, I get an error at the step of the histogram representation deployment.

Here are the logs:
```
CONFIG_FILE="/home/chloe/Documents/pims/pims-config.env" python3 ./pims/importer/import_local_images.py --path /home/chloe/Downloads/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi 
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start import and data extraction for /tmp/uploaded/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Moved /tmp/uploaded/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi to /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Finished to extract data for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start format detection for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Identified format Zeiss CZI for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start integrity check for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/original.CZI
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:/data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/original.CZI passed integrity check
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:--- SPATIAL representation deployment for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/original.CZI ---
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start converting /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi to /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Finished /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF conversion !
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start format detection for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Identified format OME-TIFF for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Start integrity check for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:/data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF passed integrity check
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Finished to deploy spatial representation at /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF
INFO:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:--- HISTOGRAM representation deployment for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/processed/visualisation.OMETIFF ---
ERROR:upload.Plate1-Blue-A-12-Scene-3-P3-F2-03.czi:Generic file error for /data/pims/upload-7c20b478-de1b-44a1-a796-677e8c6224b1/Plate1-Blue-A-12-Scene-3-P3-F2-03.czi
Traceback (most recent call last):
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/importer/importer.py", line 280, in run
    self.deploy_histogram(self.original.get_spatial())
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/importer/importer.py", line 374, in deploy_histogram
    self.histogram = build_histogram_file(
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/processing/histograms/utils.py", line 184, in build_histogram_file
    for data, c_range, z, t, ratio in extract_fn(in_image):
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/processing/histograms/utils.py", line 129, in _extract_np_thumb
    image.thumbnail(tw, th, precomputed=False, c=list(c), t=t, z=z)
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/files/image.py", line 363, in thumbnail
    return self._format.reader.read_thumb(
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/formats/common/ometiff.py", line 318, in read_thumb
    return self._read(c, z, t, self.vips_thumbnail, out_width, out_height)
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/formats/common/ometiff.py", line 311, in _read
    im = fix_rgb_interpretation(im)
  File "/home/chloe/.local/lib/python3.8/site-packages/pims/utils/vips.py", line 83, in fix_rgb_interpretation
    im = im.copy(intepretation=VIPSInterpretation.RGB16)
  File "/home/chloe/.local/lib/python3.8/site-packages/pyvips/vimage.py", line 938, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/home/chloe/.local/lib/python3.8/site-packages/pyvips/voperation.py", line 288, in call
    raise Error('{0} does not support optional argument {1}'
pyvips.error.Error: copy does not support optional argument intepretation
```

**Comment by urubens** [comment]
Hi, this was a typo in a pims utilities. Fixed by https://github.com/Cytomine-ULiege/pims/commit/ecb9223a8410f838154b34d77252daaa0f0056ca

Is it working now ?

**Comment by chlmarchal** [comment]
Yes it works now, thanks! :)
